"""
Export dashboard-ready tables for Power BI.

Power BI connects directly to the SQLite DB, but for easy portability
(uploading to Power BI Service, or if reviewing without DB drivers
installed), this script also exports flat CSVs of the key summary
tables a risk-monitoring dashboard would use.

Output: outputs/dashboard_patient_level.csv
        outputs/dashboard_risk_summary.csv
        outputs/dashboard_feature_importance.csv
"""

import pandas as pd

CLEAN_PATH = "../data/clean_kidney_disease.csv"
OUT_DIR = "../outputs"


def main():
    df = pd.read_csv(CLEAN_PATH)

    # Patient-level table, trimmed to dashboard-relevant columns
    dashboard_cols = [
        "age_of_the_patient", "blood_pressure", "target", "risk_level",
        "estimated_glomerular_filtration_rate", "serum_creatinine",
        "blood_urea", "hemoglobin_level", "cystatin_c_level",
        "hypertension", "diabetes_mellitus", "coronary_artery_disease",
        "body_mass_index", "smoking_status",
        "family_history_of_chronic_kidney_disease",
    ]
    df[dashboard_cols].to_csv(f"{OUT_DIR}/dashboard_patient_level.csv", index=False)

    # Risk summary (already built in step 2, re-exported here for convenience)
    summary = (
        df.groupby(["target", "risk_level"])
        .agg(
            patient_count=("target", "count"),
            avg_age=("age_of_the_patient", "mean"),
            avg_egfr=("estimated_glomerular_filtration_rate", "mean"),
            avg_serum_creatinine=("serum_creatinine", "mean"),
            avg_blood_pressure=("blood_pressure", "mean"),
            pct_hypertension=("hypertension", lambda s: (s == "yes").mean() * 100),
            pct_diabetes=("diabetes_mellitus", lambda s: (s == "yes").mean() * 100),
        )
        .round(2)
        .reset_index()
        .sort_values("risk_level")
    )
    summary.to_csv(f"{OUT_DIR}/dashboard_risk_summary.csv", index=False)

    # Feature importance (copy over, already generated by model script)
    fi = pd.read_csv(f"{OUT_DIR}/feature_importance.csv")
    fi.head(15).to_csv(f"{OUT_DIR}/dashboard_feature_importance.csv", index=False)

    print("Dashboard-ready exports created:")
    print(f"  {OUT_DIR}/dashboard_patient_level.csv  ({len(df)} rows)")
    print(f"  {OUT_DIR}/dashboard_risk_summary.csv    ({len(summary)} rows)")
    print(f"  {OUT_DIR}/dashboard_feature_importance.csv (top 15 features)")
    print("\nImport these into Power BI (Get Data > Text/CSV) to build:")
    print("  - A risk distribution bar/donut chart (dashboard_risk_summary)")
    print("  - A patient table with slicers by risk level, age, comorbidities")
    print("  - A feature importance chart (dashboard_feature_importance)")


if __name__ == "__main__":
    main()
